services:
  - type: web
    name: flask-video-gen-app
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 600
    envVars:
      - key: GEMINI_API_KEY
        sync: false
